### 3.7  프라미스 API 복습
- ES6 Promise API 복습

#### 3.7.1 new Promise( ) 생성자

- Promise( ) 생성자는 항상 new와 함께 사용하며 동기적으로/즉시 호출할 콜백함수를 전달해야 한다.
- 콜백 2개를 넘기고 보통은 resolve( ), reject( )로 명명한다.
- reject( )는 그냥 프라미스를 버리지만, resolve는 넘어온 값을 보고 이룸/버림 중 한가지로 처리한다.

```javascript
    var p = new Promise(function(resolve, reject) {
        // 'resolve()'는 성공
        // 'reject( )'는 실패
    });
```

#### 3.7.2 Promise.resolve( )와 Promise.reject( )

- Promise.reject( )는 이미 버려진 프라미스를 생성하는 지름길이다. 따라서, 두 프라미스는 본질적으로 동등하다.

```javascript
    var p1 = new Promise(function(resolve, reject){
        reject("허걱");
    });

    var p2 = Promise.reject("허걱");
```

- Promise.reject( )와 마찬가지로 Promise.resolve( )는 이미 이루어진 프라미스를 생성하는 용도로 사용된다.
- Promise.resolve( )는 데너블 값을 재귀적으로 풀어보고 그 최종 귀결값(이룸/버림)이 결국 반환된 프라미스에 해당한다. ( 데너블이 먼지 ?)

```javascript
    var fulfilledTh = {
        then: function(cb) {
            cb(42);
        }
    };

    var rejectedTh = {
        then: function(cb, errCb) {
            errCb("Oops");
        }
    };

    var p1 = Promise.resolve( fulfilledTh ); // 이룸 프라미스
    var p2 = Promise.resolve( rejectedTh ); // 버림 프라미스
```

#### 3.7.3 then( )과 catch( )

- 각 프라미스 인스턴스엔 then( ), catch( ) 메서드가 들어있고 프라미스에 이룸/버림 처리기를 등록할 수 있다. ( 프라미스가 귀결되면 두 처리가 중 딱 하나만 언제나 비동기적으로 호출됨)
- then( )은 하나 또는 2개의 인자를 받는데 첫 번째는 이룸 콜백, 두 번째는 버림 콜백이다. 어느 한쪽을 누락하거나 함수가 아닌 값으로 지정하면 각각 기본 콜백으로 대체된다.
- catch( )는 버림 콜백 하나만 받고 이룸 콜백은 기본 이룸 콜백으로 대체한다. ( then( null, ) 즉, catch로 이룸 콜백을 받을 수 없음.)

```javascript
    p.then( fullfilled )

    p.then( fulfilled, rejected)

    p.catch( rejected ); // 또는 p.then(null, rejected)

```

- then( ), catch( )도 새 프라미스를 만들어 반환하므로 프라미스 연쇄 형태로 흐름제어를 표현할 수 있다. ( Promise Chaining )

#### 3.7.4 Promise.all([ ])과 Promise.race([ ])
- Promise.all([ ]), Promise.race([ ])는 프라미스를 생성하여 반환하는 ES6 프라미스 API의 정적 헬퍼 유틸리티다.
- Promise.all([ ])은 주어진 모든 프라미스들이 이루어져야 메인 프라미스도 이루어지고 단 하나라도 버려지게 되면 메인 반환 프라미스 역시 곧바로 폐기된다. ( 즉, 하나라도 실패하면 성공된 모든 프라미스들도 무시된다.) -> 성공하면 프라미스의 이룸값들이 담긴 배열을, 실패하면 실패한 이유를 return 받는다.
- Promise.race([ ])는 오직 최초로 귀결된 프라미스만 승자가 되고 그 귀결 값을 반환할 프라미스의 귀결 값으로 삼는다. ( 가장 먼저 귀결된 프라미스가 성공이든 실패이든.... )

```javascript
    var p1 = Promise.resolve(42);
    var p2 = Promise.resolve("Hello, Wolrd");
    var p3 = Promise.reject("허걱");

    Promise.race( [p1, p2, p3] )
    .then( function(msg){
        console.log( msg ); // 42 -> 왜 42가 먼저 나오는지? race안의 배열 순서대로 호출이 되는지 ?
    });
    Promise.all( [p1, p2, p3 ])
    .catch( function(err) {
        console.error( err ); // "허걱"
    });
    Promise.all( [p1, p2])
    .then( function(msgs) {
        console.log(msgs); // [42, "Hello, World"]
    });
```

### 3.8 프라미스 한계

#### 3.8.1 시퀀스 에러 처리
- 프라미스의 설계 상 한계탓에 프라미스 연쇄에서 에러가 나면 그냥 조용히 묻혀버리기 쉽다.
- 프라미스의 전체 연쇄를 하나의 "뭔가"로 가리킬 개체가 없다. 즉, 밖에서는 해당 프라미스 체이닝의 에러를 감지할 수 없다.
- 에러 처리기가 없는 프라미스 연쇄에서 에러가 발생하면 나중에 어딘가에서 감지될 때까지 연쇄를 따라 죽 하위로 전파한다. -> 이런 경우라면 연쇄의 마지막 프라미스를 가리키는 레퍼런스만 갖고 있으면 여기에 버림처리기를 등록하여 에러를 잡을 수 있다.

```javascript
    var p = foo(42)
    .then(STEP2)
    .then(STEP3)
```

- p가 가리키는 대상은 then(STEP3) 호출후 마지막 반환된 프라미스다.
- 프라미스 연쇄는 각 단계에서 자신의 에러를 감지하여 처리할 방법 자체가 없으니 P에 에러 처리기를 달아놓으면 연쇄 어디에서 에러가 나도 이를 받아 처리할 수 있다.

```javascript
    p.catch( handleErrors );
```

- 하지만, 연쇄의 어느 단계에서 나름대로 에러 처리를 하면 handleErrors( )는 에러를 감지할 방법이 없다. ( catch 잡기전 then의 2번째 인자로 에러를 잡을 경우 ?)

#### 3.8.2 단일값
- 프라미스는 정의상 하나의 이룸값, 아니면 하나의 버림값을 가진다.

##### 값을 분할
- 가끔은 이럴 때 2개 이상의 프라미스로 분해해보면 해결의 실마리를 찾을 수 있다.
- 두 값(x, y)를 비동기적으로 만들어내는 유틸리티 foo( )를 생각해보자.

```javascript
    function getY(x) {
        return new Promise(function(resolve, reject) {
            setTimeout(function( ){
                resolve((3*x) -1);
            }, 100);
        });
    }

    function foo(bar, baz) {
        var x = bar * baz;
        return getY(x)
        .then(function(y){
            return [x, y]; // promise.then안에서 에러가 발생하면 reject, 값을 리턴하면 resolve(값), 리턴을 안하면 기본 프라미스가 return됨 ( 받는 쪽에서 .then을 호출할 경우)
        });
    }

    foo(10, 20)
    .then(function(msgs){
        var x = msgs[0];
        var y = msgs[1];
        console.log(x, y); // 200, 599
    });
```

- 먼저 x, y를 하나의 array 값으로 감싸서 프라미스 하나로 전달할 필요가 없도록 foo( )가 반환하는 것을 조정하자.

```javascript
    function foo(bar, baz) {
        var x = bar * baz;

        // 두 프라미스를 반환한다.
        return [
            Promise.resolve(x), // 만약, x로 하면 아래 then에 값 못받음.
            getY(x)
        ];
    }

    Promise.all(
        foo(10, 20)
    )
    .then(function(msgs){
        var x = msgs[0];
        var y = msgs[1];
        console.log(x, y);
    });

```